version: "3.3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    #ports:
    #  - '3001:3001'
    restart: on-failure
    container_name: backend
    volumes:
      - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
    env_file:
      - ./env/backend.env
  mongo:
    image: 'mongo'
    container_name: 'mongo-db'
    ports:
      - '27017-27019:27017-27019'
    volumes: 
      - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./db/mongo-volume:/data/db
    env_file:
      - ./env/mongo.env